// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbvmyohoywfseebjzfaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impidm15b2hveXdmc2VlYmp6ZmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDU5MDIsImV4cCI6MjA1NzM4MTkwMn0.QvjThfmEfh7UNse2WaJqyl1zWPPtb3yzaU3CCGrcoD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);